version: 2.1

executors:
  default-executor:
    docker:
      - image: circleci/node:14 # Choose the Node.js version you need

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - build:
          filters:
            branches:
              ignore:
                - main
